routes/web.php
<?php

use App\Http\Controllers\Auth\LoginSocialiteController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\PerfilController;
use App\Http\Controllers\SorteosController;
use App\Http\Controllers\WebController;
use Illuminate\Foundation\Auth\EmailVerificationRequest;
use Illuminate\Support\Facades\Request;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/',[WebController::class,'home']);
Route::get('/politica',[WebController::class,'politica']);

//Route::get('login/{provider}',[LoginSocialiteController::class,'redirect']);
//Route::get('login/{provider}/callback',[LoginSocialiteController::class,'callback']);
//
//Route::get("politica",[HomeController::class,'politica']);
//
//Auth::routes(['register' => true,'reset'=>true,'verify'=>true]);
//
//Route::middleware("verified")->group(function(){
//    Route::get('/dashboard', [HomeController::class, 'index'])->name('home');
//
//    //PERFIL
//    Route::prefix("perfil")->group(function(){
//        Route::get('editar', [PerfilController::class, 'show'])->name('sorteo.index');
//        Route::put('editar', [PerfilController::class, 'update']);
//
////        Route::get('oauth', [OAuthController::class, 'edit'])->name('login.oauth');
////        Route::put('oauth', [OAuthController::class, 'update']);
//    });
//
//    //SORTEOS
//    Route::prefix("sorteos")->group(function(){
//        Route::get('/', [SorteosController::class, 'index'])->name('sorteo.index');
//        Route::get('registrar', [SorteosController::class, 'create'])->name('sorteo.registrar');
//        Route::post('registrar', [SorteosController::class, 'store']);
//    });
//});

//Login
Route::get('login',[LoginController::class,'showLoginForm'])->name('login');
Route::post('login',[LoginController::class,'login']);

//Logout
Route::post('logout',[LoginController::class,'logout'])->name('logout');

//Register
Route::get('register',[RegisterController::class,'showRegistrationForm'])->name('register');
Route::post('register',[RegisterController::class,'register']);

//Reset password
Route::get('password/reset',[ForgotPasswordController::class,'showLinkRequestForm'])->name('password.request');
Route::post('password/email',[ForgotPasswordController::class,'sendResetLinkEmail'])->name('password.email');
Route::get('password/reset/{token}',[ResetPasswordController::class,'showResetForm'])->name('password.reset');
Route::post('password/reset',[ResetPasswordController::class,'reset'])->name('password.update');

//Confirm
Route::get('password/confirm', [ConfirmPasswordController::class,'showConfirmForm'])->name('password.confirm');
Route::post('password/confirm',  [ConfirmPasswordController::class,'confirm']);

//Email verification
Route::get('email/verify', [VerificationController::class,'show'])->name('verification.notice');
Route::get('email/verify/{id}/{hash}', [VerificationController::class,'verify'])->name('verification.verify');
Route::post('email/resend', [VerificationController::class,'resend'])->name('verification.resend');

Route::prefix("intranet")->name("intranet.")->group(function() {

    Route::get('/', function () {
        return redirect()->route('intranet.home');
    });



    //DASHBOARD
    Route::get('/dashboard', [HomeController::class, 'index'])->name('home');
    //CLIENTES
    Route::name("clientes.")->group(function(){
        Route::get('clientes', [ClientesController::class,"index"])->name("listado");

        Route::get('clientes/registrar', [ClientesController::class,"create"])->name('crear');
        Route::post('clientes/registrar', [ClientesController::class,"store"]);
        Route::get('clientes/{id_cliente}/editar', [ClientesController::class,"edit"])->name('editar');
        Route::put('clientes/{id_cliente}/editar', [ClientesController::class,"update"]);
//    Route::delete('clientes/{id_cliente}/eliminar', 'ClientesController@edit');
    });

    //PEDIDOS
    Route::name("pedidos.")->group(function(){
        Route::get('pedidos', [PedidosController::class,"index"])->name("listado");

        //PEDIDO - PASO 0 - Seleccionar cliente
//        Route::get('pedidos/registrar', [PedidosController::class,"create"])->name('crear');
        Route::post('pedidos/registrar', [PedidosController::class,"store"])->name('registrar');

        //PEDIDO - PASO 1 - Agregar productos
        Route::get('pedidos/{id_pedido}/carrito',  [PedidosController::class,"carrito"])->name('carrito');
        Route::put('pedidos/{id_pedido}/carrito',  [PedidosController::class,"updateCarrito"])->name('detalle.actualizar');
        Route::post('pedidos/{id_pedido}/carrito',  [PedidosController::class,"addProducto"]);
        Route::delete('pedidos/{id_pedido}/carrito',  [PedidosController::class,"removeProducto"])->name('detalle.eliminar');

        //PEDIDO - PASO 2 - Actualizar datos de cliente
        Route::get('pedidos/{id_pedido}/cliente',  [PedidosController::class,"cliente"])->name('cliente');
        Route::put('pedidos/{id_pedido}/cliente',  [PedidosController::class,"updateCliente"]);

        //PEDIDO - PASO 3 - Programar entrega
        Route::get('pedidos/{id_pedido}/programar',  [PedidosController::class,"programar"])->name('programar');
        Route::put('pedidos/{id_pedido}/programar',  [PedidosController::class,"updateProgramar"]);

        //PEDIDO - PASO 4 - Seleccionar ubicacion
        Route::get('pedidos/{id_pedido}/entrega', [PedidosController::class,"entrega"])->name('entrega');
        Route::put('pedidos/{id_pedido}/entrega', [PedidosController::class,"storeEntrega"]);

        //PEDIDO - PASO 5 - Confirmar
        Route::get('pedidos/{id_pedido}/resumen', [PedidosController::class,"resumen"])->name('resumen');
        Route::post('pedidos/{id_pedido}/resumen', [PedidosController::class,"storeResumen"]);

//    Route::delete('clientes/{id_cliente}/eliminar', 'ClientesController@edit');

        //PEDIDO - PASO 4 - Confirmar pedido

        //PEDIDO - VISUALIZAR CONFIRMADO
        Route::get('pedidos/{id_pedillo}/visualizar',[PedidosController::class,"show"])->name('visualizar');
    });

    //PRODUCCION
    Route::name("produccion.")->group(function() {
        Route::get('produccion', [ProduccionController::class, "index"])->name("listado");
        Route::post('produccion', [ProduccionController::class, "store"])->name("actualizar");
    });

    //DESPACHOS
    Route::name("entregas.")->group(function() {
        Route::get('entregas', [EntregasController::class, "index"])->name("listado");
        Route::post('entregas', [EntregasController::class, "store"])->name("actualizar");
    });

    //PRODUCTOS
    Route::name("productos.")->group(function(){
        Route::get('productos', [ProductosController::class,"index"])->name("listado");

        Route::get('productos/registrar', [ProductosController::class,"create"])->name('crear');
        Route::post('productos/registrar', [ProductosController::class,"store"]);
        Route::get('productos/{id_producto}/editar',[ProductosController::class,"edit"])->name('editar');
        Route::put('productos/{id_producto}/editar', [ProductosController::class,"update"]);
//    Route::delete('clientes/{id_cliente}/eliminar', 'ClientesController@edit');
    });

    Route::name("tarifas.")->group(function(){
        Route::get('tarifas', [TarifasController::class,"index"])->name("listado");

        Route::get('tarifas/registrar', [TarifasController::class,"create"])->name('crear');
        Route::post('tarifas/registrar', [TarifasController::class,"store"]);
        Route::get('tarifas/{id_tarifa}/editar',[TarifasController::class,"edit"])->name('editar');
        Route::put('tarifas/{id_tarifa}/editar', [TarifasController::class,"update"]);
//    Route::delete('clientes/{id_cliente}/eliminar', 'ClientesController@edit');
    });

});

app/Http/Controllers/Intranet/ClientesController.php
<?php

namespace App\Http\Controllers\Intranet;

use App\Http\Controllers\Controller;
use App\Models\Cliente;
use App\Models\Pedido;
use Illuminate\Http\Request;

class ClientesController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        //
        $filtrar=$request->get('filtrar');
        $clientes=Cliente::filtrar($filtrar)->paginate(10);
        foreach($clientes as $cliente){
            $cliente->url_editar=route('intranet.clientes.editar',$cliente->id);
            $cliente->url_pedido=route('intranet.pedidos.registrar');
        }

        $data=compact('clientes','filtrar');
        return view('intranet.clientes.listado',$data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $cliente=new Cliente();
        $data=compact('cliente');
        return view('intranet.clientes.formulario',$data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
//        $this->validate($request,[
//           'nombre'=>'required'
//        ]);

        $cliente=new Cliente();
        $cliente->alias=$request->get('alias');
        $cliente->nombres=$request->get('nombre');
        $cliente->apellidos=$request->get('apellido');
        $cliente->correo=$request->get('correo');
        $cliente->telefono=$request->get('telefono');

        $cliente->save();

        if($request->input('guardar')=="guardar_pedido"){
            $pedido=new Pedido();
            $pedido->id_cliente=$cliente->id;
            $pedido->save();
            return redirect()->route('intranet.pedidos.carrito',$pedido->id);
        }else{
            return redirect()->route('intranet.clientes.listado');
        }


    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $cliente=Cliente::findOrFail($id);
        $data=compact('cliente');
        return view('intranet.clientes.formulario',$data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $cliente=Cliente::findOrFail($id);
        $cliente->alias=$request->get('alias');
        $cliente->nombres=$request->get('nombre');
        $cliente->apellidos=$request->get('apellido');
        $cliente->correo=$request->get('correo');
        $cliente->telefono=$request->get('telefono');
        $cliente->save();

        return redirect()->route('intranet.clientes.listado');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Intranet/EntregasController.php
<?php

namespace App\Http\Controllers\Intranet;

use App\Http\Controllers\Controller;
use App\Models\Despacho;
use App\Models\Pedido;
use Carbon\Carbon;
use Illuminate\Http\Request;

class EntregasController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth:intranet');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        //
        //
        $filtrar=$request->get('filtrar');
        $despachos=Despacho::conPedidoListo()
            ->orderBy('estado','desc')
            ->orderBy('p.entrega','asc')
            ->paginate(10);


//        foreach($pedidos as $pedido){
//            $pedido->url_editar=route('intranet.pedidos.carrito',$pedido->id);
//            $pedido->url_confirmado=route('intranet.pedidos.visualizar',$pedido->id);
//        }

        $data=compact('despachos','filtrar');
        return view('intranet.entregas.listado',$data);

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //

        $id_despacho=$request->input('id_despacho');
        $despacho=Despacho::findOrFail($id_despacho);
        $despacho->estado=Despacho::ESTADO_ENTREGADO;
        $despacho->entregado=Carbon::now();
        $despacho->save();

        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Intranet/HomeController.php
<?php

namespace App\Http\Controllers\Intranet;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth:intranet');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('intranet.home');
    }
}

app/Http/Controllers/Intranet/ProduccionController.php
<?php

namespace App\Http\Controllers\Intranet;

use App\Http\Controllers\Controller;
use App\Models\Pedido;
use Illuminate\Http\Request;

class ProduccionController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth:intranet');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        //
        $filtrar=$request->get('filtrar');
        $pedidos=Pedido::filtrar($filtrar)->conEstado(Pedido::ESTADO_CONFIRMADO)
                    ->orderBy("estado_produccion","desc")->orderBy("entrega","asc")->paginate(10);


        foreach($pedidos as $pedido){
//            $pedido->url_editar=route('intranet.pedidos.carrito',$pedido->id);
//            $pedido->url_confirmado=route('intranet.pedidos.visualizar',$pedido->id);
        }

        $data=compact('pedidos','filtrar');
        return view('intranet.produccion.listado',$data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $id_pedido=$request->input('id_pedido');
        $pedido=Pedido::findOrFail($id_pedido);
        $pedido->estado_produccion=Pedido::ESTADO_PRODUCCION_LISTO;
        $pedido->save();

        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

}

resources/views/intranet/pedidos/carrito.blade.php
@extends('layouts.intranet')
@section('menu')
    @include('intranet.menu')
@endsection
@section('content')
    <div class="container">
        <div class="">
            <h4 class="float-left">Seleccionar productos - {{ $pedido->getCodigoNumerado() }}</h4>
            <a href="{{ route('intranet.pedidos.listado') }}" class="float-right btn btn-secondary mb-2">Volver</a>
            <div class="clearfix"></div>
            <form method="post">
                @csrf
{{--               <div class="row">--}}
{{--                   <div class="form-group col-2">--}}
{{--                       <label for="cliente">Nº pedido</label>--}}
{{--                       <input type="text" class="form-control" id="cliente" name="" aria-describedby="clienteHelp" placeholder="Ingresa un nombre/razon social" value="{{ sprintf("%'.04d\n", $pedido->id) }}">--}}
{{--                   </div>--}}
{{--                   <div class="form-group col-10">--}}
{{--                       <label for="cliente">Cliente</label>--}}
{{--                       <input type="text" class="form-control" id="cliente" name="cliente" aria-describedby="clienteHelp" placeholder="Ingresa un nombre/razon social" value="{{ old('cliente',$pedido->cliente) }}">--}}
{{--                   </div>--}}
{{--               </div>--}}

                <div class="form-group form-inline">
                    <label for="cliente">Agregar producto </label>
                    <select name="tarifa" id="" class="form-control">
                        @foreach($tarifas as $tarifa)
                            <option value="{{ $tarifa->id }}">{{ $tarifa->getDescripcion()."  =>  S/.".$tarifa->precio_unitario }}</option>
                        @endforeach
                    </select>
                    <button type="submit" class="btn btn-success">Añadir</button>
                </div>


            </form>

            <table class="table table-bordered table-sm">
                <thead class="thead-light">
                <tr>
                    {{--                <th scope="col">#</th>--}}
                    <th scope="col">Producto</th>
                    <th scope="col">Cantidad</th>
                    <th scope="col">Precio</th>
                    <th scope="col">Subtotal</th>
                    <th scope="col">Opciones</th>
                </tr>
                </thead>
                <tbody>
                @isset($detallePedido)
                    @forelse($detallePedido as $detalle)
                        <tr>
                            {{--                        <th></th>--}}
                            <td>{{$detalle->producto}}</td>
                            <td>
                                <form action="{{ $detalle->url_actualizar }}" method="post"  class="form-inline">
                                    @csrf
                                    @method('put')
                                    <input type="hidden" name="id_detalle" value="{{$detalle->id}}">
                                    <button type="submit" name="accion" class="btn btn-danger btn-sm d-none" value="0"> - </button>
                                    <button type="submit" name="accion" class="btn btn-danger btn-sm " value="-1"> - </button>
                                    <input type="text" name="cantidad" class="form-control " value="{{ $detalle->cantidad }}">
                                    <button type="submit" name="accion" class="btn btn-success btn-sm " value="1"> + </button>
                                </form>
                                </td>
                            <td>{{$detalle->precio}}</td>
                            <td>{{$detalle->subtotal}}</td>
                            <td>
                                <form action="{{ $detalle->url_eliminar }}" method="post" >
                                    @csrf
                                    @method('delete')
                                    <input type="hidden" name="id_detalle" value="{{ $detalle->id }}">
                                    <button type="submit" class="btn btn-danger btn-sm">Eliminar</button>
                                </form>

                            </td>
                        </tr>
                    @empty
                        <tr>
                            <td colspan="5"> No hay resultados</td>
                        </tr>
                    @endforelse
                    <tr>
                        <th colspan="3" class="text-right">Total</th>
                        <th>{{ $pedido->total }}</th>
                    </tr>
                @else
                    <tr>
                        <td  colspan="5"> No se han definido datos</td>
                    </tr>
                @endisset
                </tbody>
            </table>

           <div class="row">
               <div class="col-10">
                   <div class="progress" style="height: 3em">
                       <div class="progress-bar" role="progressbar" style="width: 25%;" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100">Paso 1: Seleccionar productos </div>
                   </div>
               </div>

               <div class="col-2">
                   @if($pedido->total>0 && $pedido->detallePedido->count()>0)
                       <a href="{{ $pedido->url_cliente }}" class="btn btn-warning float-right">Continuar</a>
                   @endif
               </div>
           </div>
        </div>
    </div>
@endsection

resources/views/intranet/pedidos/cliente.blade.php
@extends('layouts.intranet')
@section('menu')
    @include('intranet.menu')
@endsection
@section('content')
    <div class="container">
        <div class="">
            <h4 class="float-left">Actualizar datos de cliente  - {{ $pedido->getCodigoNumerado() }}</h4>
            <a href="{{ route('intranet.pedidos.listado') }}" class="float-right btn btn-secondary mb-2">Volver al listado de pedidos</a>
            <div class="clearfix"></div>
            <form method="post" class="form">
                @csrf
                @if($pedido->id>0)
                    @method('PUT')
                @endif
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="nombre">Nombre</label>
                        <input type="text" class="form-control" id="nombre" name="nombre" aria-describedby="clienteHelp" placeholder="Ingresa un nombre" value="{{ old('nombre',$cliente->nombres) }}">
                    </div>
                    <div class="form-group col-md-6">
                        <label for="apellido">Apellido</label>
                        <input type="text" class="form-control" id="apellido" name="apellido" aria-describedby="clienteHelp" placeholder="Ingresa un apellido" value="{{ old('apellido',$cliente->apellidos) }}">
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="telefono">Teléfono</label>
                        <input type="text" class="form-control" id="telefono" name="telefono" placeholder="Ingrese un telefono" value="{{ old('telefono',$cliente->telefono) }}">
                    </div>
                    <div class="form-group col-md-6">
                        <label for="correo">Correo</label>
                        <input type="email" class="form-control" id="correo" name="correo" aria-describedby="emailHelp" placeholder="Ingrese un correo" value="{{ old('correo',$cliente->correo) }}">
                        {{--                    <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>--}}
                    </div>
                </div>
{{--                <div class="form-row">--}}
{{--                    <div class="form-group col-md-6">--}}
{{--                        <label for="inputAddress">Dirección</label>--}}
{{--                        <input type="text" class="form-control" id="direccion" name="direccion" placeholder="Ingrese una dirección" value="{{old('direccion',$cliente->direccion)}}">--}}
{{--                    </div>--}}
{{--                    <div class="form-group col-md-6">--}}
{{--                        <label for="inputAddress">Referencia</label>--}}
{{--                        <input type="text" class="form-control" id="referencia" name="referencia" placeholder="Ingrese una referencia" value="{{old('referencia',$cliente->referencia)}}">--}}
{{--                    </div>--}}
{{--                </div>--}}
                <button type="submit" class="btn btn-primary">Guardar</button>
            </form>
            <div class="row">
                <div class="col-10">
                    <div class="progress" style="height: 3em">
                        <div class="progress-bar" role="progressbar" style="width: 25%;" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100">Paso 1: Seleccionar productos </div>
                        <div class="progress-bar" role="progressbar" style="width: 25%;" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100">Paso 2: Datos de contacto </div>
                    </div>
                </div>

                <div class="col-2">
                    @if($pedido->total>0 && $pedido->detallePedido->count()>0)
                        <a href="{{ $pedido->url_programar }}" class="btn btn-warning float-right">Continuar</a>
                    @endif
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/intranet/pedidos/completo.blade.php
@extends('layouts.intranet')
@section('menu')
    @include('intranet.menu')
@endsection
@section('content')
    <div class="container">
        <div class="">
            <h4 class="float-left">Seleccionar productos</h4>
            <a href="{{ route('intranet.pedidos.listado') }}" class="float-right btn btn-secondary mb-2">Volver</a>
            <div class="clearfix">

            </div>
            <form method="post">
                @csrf

                <div class="form-group">
                    <label for="cliente">Cliente</label>
                    <input type="text" class="form-control" id="cliente" name="cliente" aria-describedby="clienteHelp" placeholder="Ingresa un nombre/razon social" value="{{ old('cliente',$pedido->cliente) }}">
                </div>
            </form>

            <table class="table table-bordered">
                <thead class="thead-light">
                <tr>
                    {{--                <th scope="col">#</th>--}}
                    <th scope="col">Producto</th>
                    <th scope="col">Cantidad</th>
                    <th scope="col">Precio</th>
                    <th scope="col">Subtotal</th>
                </tr>
                </thead>
                <tbody>
                @isset($detallePedido)
                    @forelse($detallePedido as $detalle)
                        <tr>
                            {{--                        <th></th>--}}
                            <td>{{$detalle->producto}}</td>
                            <td>{{$detalle->cantidad}}</td>
                            <td>{{$detalle->precio}}</td>
                            <td>{{$detalle->subtotal}}</td>
                        </tr>
                    @empty
                        <tr>
                            <td colspan="5"> No hay resultados</td>
                        </tr>
                    @endforelse
                    <tr>
                        <th colspan="3" class="text-right">Total</th>
                        <th>{{ $pedido->total }}</th>
                    </tr>
                @else
                    <tr>
                        <td  colspan="5"> No se han definido datos</td>
                    </tr>
                @endisset
                </tbody>
            </table>
        </div>
    </div>
@endsection